name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        id: deploy
        run: |
          npm run build
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add origin https://github.com/${GITHUB_REPO}.git
          git push --force origin main:gh-pages

